# Generated by Django 4.2.10 on 2025-06-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_artisanportfolio_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanportfolio',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
